<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_AlsoViewed
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
/** @var $viewModel \Mavenbird\AlsoViewed\ViewModel\AlsoViewed */
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$_productData = $block->getProduct();
$currprodId = $_productData->getId();
$_sku = $_productData->getSku();
$category_ids = $_productData->getCategoryIds();
$current_category_id = $category_ids;
$count_sku = $helper->lastviewproduct($_sku, $current_category_id);
$_productCollection = [];
$cnt = 1;
$alsoProductLimit = $helper->getConfig('alsoviewedsection/alsoviewedgroup/limit');
$abstractProductBlock = $block->getLayout()->createBlock(\Magento\Catalog\Block\Product\AbstractProduct::class);
if (count($count_sku) > 0) {
?>
    <div class="mb-alsoviwed">
    <h2><?= $escaper->escapeHtml(__($helper->getConfig('alsoviewedsection/alsoviewedgroup/title'))) ?></h2>
    <?php
    $_helper = $viewModel->getOutputHelper();
    $imageBlock = $block->getLayout()->createBlock(\Magento\Catalog\Block\Product\Image::class);
    $listProductBlock = $block->getListProduct();
    $viewMode = 'grid';
    ?>
    <div class="products wrapper <?= $escaper->escapeHtmlAttr($viewMode) ?> products-<?= $escaper->escapeHtmlAttr($viewMode) ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php
            foreach ($count_sku as $key => $pro_value) {
                $_product = $viewModel->getProduct($key);
            ?>
                <?php if ($cnt <= $alsoProductLimit) { ?>
                    <?= ($iterator++ == 1) ? '<li style="margin-top:20px;" class="item product product-item">' : '</li><li style="margin-top:20px;" class="item product product-item">' ?>

                    <div class="product-item-info" data-container="product-grid">
                        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>" class="product photo product-item-photo" tabindex="-1"> <span style="width:240px;" class="product-image-container">
                                <span style="padding-bottom: 137%;" class="product-image-wrapper">
                                    <?php
                                    $imageUrl = $viewModel->getImageHelper()
                                        ->init($_product, 'product_page_image_large')
                                        ->constrainOnly(false)
                                        ->keepAspectRatio(true)
                                        ->keepFrame(false)
                                        ->resize(270, 371)
                                        ->getUrl();
                                    ?>
                                    <img class="product-image-photo" src="<?= $escaper->escapeUrl($imageUrl) ?>" /> </span>
                            </span>
                        </a>
                        <div class="product details product-item-details">
                            <div style="padding: 0 2px;"><?= $block->getProductDetailsHtml($_product); ?></div>
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link" href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                    <?= $escaper->escapeHtml($_helper->productAttribute($_product, $_product->getName(), 'name')) ?>
                                </a>
                            </strong>
                            <?= /* @noEscape */ $abstractProductBlock->getProductPrice($_product) ?>
                        </div>
                    </div>

                    <?= ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                    <?php $cnt++; ?>
                <?php } ?>
            <?php
            }
            ?>
        </ol>
    </div>
    </div>
<?php } ?>